update
upgrade

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed

install findutils

install bash

tap homebrew/dupes
install homebrew/dupes/grep

tap railwaycat/emacsmacport
install emacs-mac

install ack
install coreutils
install erlang
install git
install heroku-toolbelt
install hub
install jq
install python
install reattach-to-user-namespace
install redis
install riak
install tmux
install tree
install vim
install wget
install zsh

# Install homebrew-cask

tap phinze/homebrew-cask
install brew-cask

# Install osx apps

cask --appdir="/Applications" \
  alfred \
  dropbox \
  google-drive \
  one-password \
  iterm2 \
  spotify \
  slate \
  sublime-text

# Remove outdated versions from the cellar

cleanup
